name: Debug
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: Philippvs/pr-impact
          token: ${{ secrets.GITHUB_TOKEN }}
#name: PR Impact Analysis
#
#on:
#  pull_request:
#    types: [opened, synchronize, reopened]
#
#permissions:
#  contents: read
#  pull-requests: write
#
#jobs:
#  analyze:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout with full history
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#
#
#      - name: use PR Impact GH Action
#        uses: Philippvs/pr-impact@v2.5.2


