name: PR Impact Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: use PR Impact GH Action
        uses: Philippvs/pr-impact@v2.5.2
        with:
          github-token: ${{ github.token }}
          fail-on-risk: "CRITICAL"